export const COUNTRIES = [
  { name: "ALLEMAGNE", code: "DE" },
  { name: "AUTRICHE", code: "AT" },
  { name: "BELGIQUE", code: "BE" },
  { name: "BULGARIE", code: "BG" },
  { name: "CHYPRE", code: "CY" },
  { name: "CROATIE", code: "HR" },
  { name: "DANEMARK", code: "DK" },
  { name: "ESPAGNE", code: "ES" },
  { name: "ESTONIE", code: "EE" },
  { name: "FINLANDE", code: "FI" },
  { name: "FRANCE", code: "FR" },
  { name: "GRÈCE", code: "GR" },
  { name: "HONGRIE", code: "HU" },
  { name: "IRLANDE", code: "IE" },
  { name: "ITALIE", code: "IT" },
  { name: "LETTONIE", code: "LV" },
  { name: "LITUANIE", code: "LT" },
  { name: "MALTE", code: "MT" },
  { name: "LUXEMBOURG", code: "LU" },
  { name: "PAYS-BAS", code: "NL" },
  { name: "POLOGNE", code: "PL" },
  { name: "PORTUGAL", code: "PT" },
  { name: "REPUBLIQUE TCHÈQUE", code: "CZ" },
  { name: "ROUMANIE", code: "RO" },
  { name: "SLOVAQUIE", code: "SK" },
  { name: "SLOVÉNIE", code: "SI" },
  { name: "SUÈDE", code: "SE" },
  { name: "AUSTRALIE", code: "AU" },
  { name: "CANADA", code: "CA" },
  { name: "CHILI", code: "CL" },
  { name: "COLOMBIE", code: "CO" },
  { name: "CORÉE (République de)", code: "KR" },
  { name: "COSTA-RICA", code: "CR" },
  { name: "ÉTATS UNIS D'AMÉRIQUE", code: "US" },
  { name: "ISLANDE", code: "IS" },
  { name: "ISRAËL", code: "IL" },
  { name: "JAPON", code: "JP" },
  { name: "MEXIQUE", code: "MX" },
  { name: "NORVÈGE", code: "NO" },
  { name: "NOUVELLE ZÉLANDE", code: "NZ" },
  { name: "ROYAUME-UNI", code: "GB" },
  { name: "SUISSE", code: "CH" },
  { name: "TURQUIE", code: "TR" },
  { name: "AFGHANISTAN", code: "AF" },
  { name: "AFRIQUE DU SUD", code: "ZA" },
  { name: "ALBANIE", code: "AL" },
  { name: "ALGÉRIE", code: "DZ" },
  { name: "ANDORRE", code: "AD" },
  { name: "ANGOLA", code: "AO" },
  { name: "ANTILLES NÉERLANDAISES", code: "AN" },
  { name: "ARABIE SAOUDITE", code: "SA" },
  { name: "ARGENTINE", code: "AR" },
  { name: "ARMÉNIE", code: "AM" },
  { name: "ARUBA", code: "AW" },
  { name: "AZERBAÏDJAN", code: "AZ" },
  { name: "BAHAMAS", code: "BS" },
  { name: "BAHREÏN", code: "BH" },
  { name: "BANGLADESH", code: "BD" },
  { name: "BÉLIZE", code: "BZ" },
  { name: "BÉNIN", code: "BJ" },
  { name: "BERMUDES", code: "BM" },
  { name: "BHOUTAN", code: "BT" },
  { name: "BIÉLORUSSIE", code: "BY" },
  { name: "BIRMANIE (MYANMAR)", code: "MM" },
  { name: "BOLIVIE", code: "BO" },
  { name: "BOSNIE-HERZÉGOVINE", code: "BA" },
  { name: "BOTSWANA", code: "BW" },
  { name: "BRÉSIL", code: "BR" },
  { name: "BRUNEÏ", code: "BN" },
  { name: "BURKINA FASO", code: "BF" },
  { name: "BURUNDI", code: "BI" },
  { name: "CAMBODGE", code: "KH" },
  { name: "CAMEROUN", code: "CM" },
  { name: "CAP VERT", code: "CV" },
  { name: "CENTRAFRIQUE", code: "CF" },
  { name: "CHINE", code: "CN" },
  { name: "COMORES", code: "KM" },
  { name: "CONGO", code: "CG" },
  { name: "CORÉE", code: "KP" },
  { name: "COSTA RICA", code: "CR" },
  { name: "CÔTE D'IVOIRE", code: "CI" },
  { name: "CUBA", code: "CU" },
  { name: "DJIBOUTI", code: "DJ" },
  { name: "DOMINICAINE (République)", code: "DO" },
  { name: "DOMINIQUE", code: "DM" },
  { name: "ÉGYPTE", code: "EG" },
  { name: "ÉMIRATS ARABES UNIS", code: "AE" },
  { name: "ÉQUATEUR", code: "EC" },
  { name: "ÉRYTRÉE", code: "ER" },
  { name: "ÉTHIOPIE", code: "ET" },
  { name: "FÉROÉ (Îles)", code: "FO" },
  { name: "FIDJI", code: "FJ" },
  { name: "GABON", code: "GA" },
  { name: "GAMBIE", code: "GM" },
  { name: "GEORGIE", code: "GE" },
  { name: "GHANA", code: "GH" },
  { name: "GIBRALTAR", code: "GI" },
  { name: "GRENADE", code: "GD" },
  { name: "GROËNLAND", code: "GL" },
  { name: "GUAM", code: "GU" },
  { name: "GUATÉMALA", code: "GT" },
  { name: "GUINÉE", code: "GN" },
  { name: "GUINÉE ÉQUATORIALE", code: "GQ" },
  { name: "GUINEÉ-BISSAU", code: "GW" },
  { name: "GUYANA", code: "GY" },
  { name: "HAÏTI", code: "HT" },
  { name: "HONDURAS", code: "HN" },
  { name: "HONG KONG", code: "HK" },
  { name: "INDE", code: "IN" },
  { name: "INDONÉSIE", code: "ID" },
  { name: "IRAK", code: "IQ" },
  { name: "IRAN", code: "IR" },
  { name: "JAMAÏQUE", code: "JM" },
  { name: "JORDANIE", code: "JO" },
  { name: "KAZAKSTAN", code: "KZ" },
  { name: "KENYA", code: "KE" },
  { name: "KIRIBATI", code: "KI" },
  { name: "KOWEÏT", code: "KW" },
  { name: "KYRGYZSTAN", code: "KG" },
  { name: "LAOS", code: "LA" },
  { name: "LESOTHO", code: "LS" },
  { name: "LIBAN", code: "LB" },
  { name: "LIBÉRIA", code: "LR" },
  { name: "LIBYE", code: "LY" },
  { name: "LIECHTENSTEIN", code: "LI" },
  { name: "MACAO", code: "MO" },
  { name: "MACÉDOINE", code: "MK" },
  { name: "MADAGASCAR", code: "MG" },
  { name: "MALAISIE", code: "MY" },
  { name: "MALAWI", code: "MW" },
  { name: "MALDIVES", code: "MV" },
  { name: "MALI", code: "ML" },
  { name: "MALOUINES (Îles)", code: "FK" },
  { name: "MAROC", code: "MA" },
  { name: "MARSHALL (Îles)", code: "MH" },
  { name: "MAURICE", code: "MU" },
  { name: "MAURITANIE", code: "MR" },
  { name: "MICRONÉSIE", code: "FM" },
  { name: "MOLDAVIE", code: "MD" },
  { name: "MONACO", code: "MC" },
  { name: "MONGOLIE", code: "MN" },
  { name: "MONTÉNÉGRO", code: "ME" },
  { name: "MONTSERRAT", code: "MS" },
  { name: "MOZAMBIQUE", code: "MZ" },
  { name: "NAMIBIE", code: "NA" },
  { name: "NÉPAL", code: "NP" },
  { name: "NICARAGUA", code: "NI" },
  { name: "NIGER", code: "NE" },
  { name: "NIGÉRIA", code: "NG" },
  { name: "OMAN", code: "OM" },
  { name: "OUGANDA", code: "UG" },
  { name: "OUZBÉKISTAN", code: "UZ" },
  { name: "PAKISTAN", code: "PK" },
  { name: "PALAU", code: "PW" },
  { name: "PANAMA", code: "PA" },
  { name: "PAPOUASIE NOUVELLE GUINÉE", code: "PG" },
  { name: "PARAGUAY", code: "PY" },
  { name: "PÉROU", code: "PE" },
  { name: "PHILIPPINES", code: "PH" },
  { name: "PITCAÏRN", code: "PN" },
  { name: "PORTO RICO", code: "PR" },
  { name: "QUATAR", code: "QA" },
  { name: "RUSSIE", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "SAHARA OCCIDENTAL", code: "EH" },
  { name: "SAINT KITTS ET NEVIS", code: "KN" },
  { name: "SAINT VINCENT ET GRENADINES", code: "VC" },
  { name: "SAINTE HÉLÈNE", code: "SH" },
  { name: "SAINTE LUCIE", code: "LC" },
  { name: "SALVADOR", code: "SV" },
  { name: "SAMOA", code: "WS" },
  { name: "SAN MARIN", code: "SM" },
  { name: "SAO TOMÉ ET PRINCIPE", code: "ST" },
  { name: "SÉNÉGAL", code: "SN" },
  { name: "SERBIE", code: "RS" },
  { name: "SEYCHELLES", code: "SC" },
  { name: "SIERRA LÉONE", code: "SL" },
  { name: "SINGAPOUR", code: "SG" },
  { name: "SALOMON (Îles)", code: "SB" },
  { name: "SOMALIE", code: "SO" },
  { name: "SOUDAN", code: "SD" },
  { name: "SRI LANKA", code: "LK" },
  { name: "SURINAME", code: "SR" },
  { name: "SWAZILAND", code: "SZ" },
  { name: "SYRIE", code: "SY" },
  { name: "TADJIKISTAN", code: "TJ" },
  { name: "TAÏWAN", code: "TW" },
  { name: "TANZANIE", code: "TZ" },
  { name: "TCHAD", code: "TD" },
  { name: "THAÏLANDE", code: "TH" },
  { name: "TIMOR ORIENTAL", code: "TP" },
  { name: "TOGO", code: "TG" },
  { name: "TONGA", code: "TO" },
  { name: "TRINIDAD ET TOBAGO", code: "TT" },
  { name: "TUNISIE", code: "TN" },
  { name: "TURKMÉNISTAN", code: "TM" },
  { name: "UKRAINE", code: "UA" },
  { name: "URUGUAY", code: "UY" },
  { name: "VANUATU", code: "VU" },
  { name: "VÉNÉZUELA", code: "VE" },
  { name: "VIETNAM", code: "VN" },
  { name: "YEMEN", code: "YE" },
  { name: "ZAÏRE", code: "ZR" },
  { name: "ZAMBIE", code: "ZM" },
  { name: "ZIMBABWE", code: "ZW" }
].sort((a, b) => a.name.localeCompare(b.name, 'fr'));