// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fzxkiwrungrwptlueoqt.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6eGtpd3J1bmdyd3B0bHVlb3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MTk5NDgsImV4cCI6MjA0OTA5NTk0OH0.xR_5ChUbrQo5zL_Mt3bh6f_F4G0HXSmUdihZq2hSu6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);